let subtitleTopper =  'border-top-width:0.1vh; border-top-style: solid; border-top-color: white;'
on('prinston_core:character:openAppearanceMenu', () => {
  exports.menu_manager.closeMenu('prinston_core:createCharacter');
  exports.menu_manager.openMenu(
    'prinston_core:createCharacter',
    [
      { type: 'title', title: 'Appearance', subtitle: 'You are given 1 free \'plastic surgery\', meaning you can change your character\'s appearance later. Just visit the \'Plastic Surgeon\' in game' },
      { type: 'title', subtitle: 'Eyes', style: subtitleTopper },
      createScrollIndexOption(`character.visual.appearance.eye.color`, 'Color', [
        { text: '1' },
        { text: '2' },
        { text: '3' },
        { text: '4' },
        { text: '5' },
        { text: '6' },
        { text: '7' },
        { text: '8' },
        { text: '9' },
        { text: '10' },
        { text: '11' },
        { text: '12' },
        { text: '13' },
        { text: '14' },
        { text: '15' },
        { text: '16' },
        { text: '17' },
        { text: '18' },
        { text: '19' },
        { text: '20' },
        { text: '21' },
        { text: '22' },
        { text: '23' },
        { text: '24' },
        { text: '25' },
        { text: '26' },
        { text: '27' },
        { text: '28' },
        { text: '29' },
        { text: '30' },
      ]),
      createRangeOption(`character.visual.appearance.eye.open`, 'Open (%)', true),
      { type: 'title', subtitle: 'Eyebrows', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.eyebrow.height`, 'Height (%)', true),
      createRangeOption(`character.visual.appearance.eyebrow.length`, 'Extrusion (%)', false),
      { type: 'title', subtitle: 'Nose', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.nose.width`, 'Width (%)', false),
      { type: 'title', subtitle: 'Nose Tip', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.nose.peak.height`, 'Height (%)', false),
      createRangeOption(`character.visual.appearance.nose.peak.length`, 'In <- Length -> Out', true),
      createRangeOption(`character.visual.appearance.nose.peak.bend`, 'Up <- Bend -> Down', false),
      { type: 'title', subtitle: 'Nose Bone', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.nose.bone.height`, 'Height (%)', true),
      createRangeOption(`character.visual.appearance.nose.bone.twist`, 'Left <- Bend -> Right', false),
      { type: 'title', subtitle: 'Cheeks'},
      createRangeOption(`character.visual.appearance.cheek.width`, 'Puffiness (%)', true),
      { type: 'title', subtitle: 'Cheek Bones', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.cheek.bone.height`, 'Height (%)', true),
      createRangeOption(`character.visual.appearance.cheek.bone.width`, 'Depth (%)', false),
      { type: 'title', subtitle: 'Lips', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.lips`, 'Puffiness (%)', true),
      { type: 'title', subtitle: 'Jaw', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.jaw.width`, 'Width (%)', false),
      createRangeOption(`character.visual.appearance.jaw.length`, 'Size (%)', false),
      { type: 'title', subtitle: 'Chin', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.chin.height`, 'Height (%)', false),
      createRangeOption(`character.visual.appearance.chin.length`, 'Length (%)', false),
      createRangeOption(`character.visual.appearance.chin.width`, 'Width (%)', false),
      createRangeOption(`character.visual.appearance.chin.depth`, 'Depth (%)', true),
      { type: 'title', subtitle: 'Neck', style: subtitleTopper },
      createRangeOption(`character.visual.appearance.neck`, 'Width (%)', false),
      { type: 'textdisplay', value: 'Continue', prompt: 'Next: Cosmetics', onselect: 'prinston_core:character:openCosmeticMenu' }
      //{ type: 'textdisplay', value: 'Continue', prompt: 'Next: Clothing', onselect: 'prinston_core:character:complete' }
    ],
    'prinston_core:character:openInheritanceMenu'
  );
});
